language: ruby
bundler_args: --without development production --deployment --jobs=4 --retry=5
jdk: openjdk8
os: linux
rvm: jruby-9.2.13.0

env:
  global:
    # Travis CI makes encrypted variables available ONLY to pull requests coming from the same repository. Read more:
    # https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
    - ARTIFACTS_PATHS="./junction.war"
    - AWS_ACCESS_KEY_ID=${ARTIFACTS_KEY}
    - AWS_SECRET_ACCESS_KEY=${ARTIFACTS_SECRET}
    - DISPLAY=:99.0
    - JRUBY_OPTS="--dev -J-Xmx900m"
    - LOGGER_LEVEL=WARN
    - PATH="${HOME}/.local/bin:$PATH"
    - S3_PATH="/${TRAVIS_BRANCH}/$(date -u +%Y%m%d_%H%M%SZ)_${TRAVIS_COMMIT}"

# Note: the artifacts add-on does not run on pull request builds. Read https://docs.travis-ci.com/user/uploading-artifacts/
addons:
  artifacts:
    s3_region: 'us-west-2'
    debug: true
    target_paths:
      - ${S3_PATH}
  postgresql: "9.6"

before_install:
  - nvm install 12
  - gem uninstall bundler --force -x
  - gem install bundler -v '1.17.3'
  - npm config set strict-ssl false

  # Set up test db
  - psql -c "create user calcentral_test with password 'secret';" -U postgres
  - psql -c 'create database edodb_test;' -U postgres
  - psql -c 'grant all privileges on database edodb_test to calcentral_test;' -U postgres
  - psql -c 'alter database edodb_test owner to calcentral_test;' -U postgres

jobs:
  include:
    - # Lint Js
      if: type = pull_request
      script:
        - npm install
        - npm run lint-vue
        - npm run build-vue
    - # RSpec
      if: type = pull_request
      script:
        - RAILS_ENV=test bundle exec rspec
    - stage: Deploy
      if: type = push OR env(DEPLOY_JUNCTION_WAR) = true
      script:
        - npm install --production
        - npm run build-vue
        - pip install --user awscli
        - aws configure list
        - aws s3 cp s3://${ARTIFACTS_BUCKET}/third-party-dependencies/ojdbc8.jar .
        - mv ./ojdbc8.jar ./lib
        - git log --pretty=format:'%H' -n 1 > versions/git.txt
        - bundle config --delete without
        - bundle install --deployment --retry 3
        - bundle package --all
        - bundle exec rake fix_assets
        - bundle exec warble NAME=junction 2>&1 1>/dev/null
        - echo -n "${S3_PATH}/junction.war" > latest.txt
        - aws s3 cp latest.txt "s3://${ARTIFACTS_BUCKET}/${TRAVIS_BRANCH}/"
